#!/usr/bin/env python3
from __future__ import annotations

import argparse
import datetime as dt
import os
import re
import sys
import zipfile
from pathlib import Path


def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def safe_slug(value: str) -> str:
    value = re.sub(r"[^A-Za-z0-9._-]+", "-", value.strip()).strip("-._")
    return value or "semantic-module"


def find_smods(store: Path) -> list[Path]:
    return sorted(
        (p for p in store.rglob("*.smod") if p.is_file()),
        key=lambda p: p.stat().st_mtime_ns,
        reverse=True,
    )


def choose_root(store: Path, smod: Path) -> Path:
    parent = smod.parent
    if parent.name.lower() == "modules":
        sibling = parent / smod.stem
        if sibling.is_dir():
            return sibling
    return parent


def build_zip(source: Path, smod: Path, zip_path: Path) -> None:
    files = [p for p in source.rglob("*") if p.is_file()]
    if smod not in files:
        files.append(smod)
    if not files:
        fail(f"No imported files found under {source}")

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, allowZip64=True) as zf:
        for path in sorted(set(files)):
            try:
                rel = path.relative_to(source)
            except ValueError:
                rel = Path(path.name)
            lowered = rel.as_posix().lower()
            if lowered.endswith((".lock", ".tmp", ".part")):
                continue
            zf.write(path, rel.as_posix())


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--store", required=True)
    ap.add_argument("--module-name", required=True)
    ap.add_argument("--output-dir", required=True)
    args = ap.parse_args()

    store = Path(args.store).expanduser().resolve()
    out = Path(args.output_dir).expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)

    if not store.exists():
        fail(f"Semantic module store does not exist: {store}")

    smods = find_smods(store)
    if not smods:
        fail(f"Import completed but no .smod was found under {store}")

    smod = smods[0]
    root = choose_root(store, smod)
    slug = safe_slug(args.module_name)
    version = os.environ.get("RELEASE_VERSION", "").strip()

    if version:
        v = safe_slug(version)
        if v.lower().startswith("v"):
            tag = f"{slug}-{v}"
            asset = f"{slug}-{v}.zip"
        else:
            tag = f"{slug}-v{v}"
            asset = f"{slug}-v{v}.zip"
    else:
        stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d-%H%M%S")
        tag = f"{slug}-{stamp}"
        asset = f"{slug}-{stamp}.zip"

    zip_path = out / asset
    build_zip(root, smod, zip_path)

    with zipfile.ZipFile(zip_path) as zf:
        smod_names = [n for n in zf.namelist() if n.lower().endswith(".smod")]
        if len(smod_names) != 1:
            fail(f"Generated ZIP must contain exactly one .smod, found {len(smod_names)}: {smod_names}")

    language = os.environ.get("SOURCE_LANGUAGE", "")
    package = os.environ.get("SOURCE_PACKAGE", "")
    now = dt.datetime.now(dt.timezone.utc).isoformat()

    (out / "RELEASE_NOTES.md").write_text(
        f"""# {args.module_name}\n\n"
        f"Automatically generated by the Semantic foreign-package import workflow.\n\n"
        f"- Source language: `{language}`\n"
        f"- Source package: `{package}`\n"
        f"- Semantic manifest: `{smod.name}`\n"
        f"- Generated UTC: `{now}`\n\n"
        f"Install with:\n\n```bash\n"
        f"sp module import https://github.com/SemanticProgrammingLanguage/Semantic-Module-Store/releases/download/{tag}/{asset}\n"
        f"```\n\n"
        f"The archive was produced using the latest `main` revision of `tarekwasfy01/Code-Transpiler` at workflow runtime.\n""",
        encoding="utf-8",
    )

    (out / "release.env").write_text(
        "\n".join([
            f"MODULE_NAME={args.module_name}",
            f"RELEASE_TAG={tag}",
            f"RELEASE_ASSET_NAME={asset}",
            f"RELEASE_ZIP={zip_path}",
            f"IMPORTED_SMOD={smod}",
            f"IMPORTED_MODULE_ROOT={root}",
        ]) + "\n",
        encoding="utf-8",
    )

    print(f"Store:       {store}")
    print(f"Manifest:    {smod}")
    print(f"Module root: {root}")
    print(f"ZIP:         {zip_path}")
    print(f"Tag:         {tag}")


if __name__ == "__main__":
    main()
